### ISSUE TITLE
Complete source?

### ISSUE THREAD

**Issue by grapefrukt** [furusystems/openfl-xinput#1]
This extension is great, but I'm having some trouble to get it to work for Windows XP, I suspect it was built against a too new version of Direct X. I could probably fix that myself, but the source for the extension itself is sadly missing. 

Is that something you could be persuaded to post?

**Comment by Sunjammer** [comment]
Of course, it's in the repo now :)

I didn't know where to put that stuff since the whole thing was supposed to be very haxelibby, but I guess it doesn't actually matter. Good to have it archived somewhere public. Hope it helps.
